//! SQL helpers consumed by the `sql` and `sql_query` endpoints generated by
//! `#[derive(DbmsCanister)]` when the `sql` feature is enabled.
//!
//! The statement is parsed here before it reaches the engine, so the
//! canister can check it first:
//!
//! - tables reserved for ic-dbms (`ic_dbms_*`) do not exist for SQL;
//! - every table the statement touches is checked against the ACL with the
//!   same rules as the typed endpoints;
//! - `BEGIN`, `COMMIT` and `ROLLBACK` go through the transaction ownership
//!   ledger.

use candid::Principal;
use ic_dbms_api::prelude::{
    AclPermission, DeleteBehavior, IcDbmsError, IcDbmsResult, SqlError, SqlResult, TransactionId,
    Value,
};
use wasm_dbms::prelude::{DatabaseSchema, WasmDbmsDatabase};
use wasm_dbms_sql::SqlEngine;
use wasm_dbms_sql::ast::Statement;

use super::{assert_caller_owns_transaction, delete_tables};
use crate::acl::{self, RESERVED_TABLE_PREFIX};
use crate::memory::{DBMS_CONTEXT, IcMemoryProvider};
use crate::schema::CanisterSchema;
use crate::transaction;

/// Message of the [`ic_dbms_api::prelude::SqlError::Unsupported`] error
/// returned by [`sql_query`] for a statement that is not a `SELECT`.
pub const SQL_QUERY_READ_ONLY: &str =
    "sql_query only runs SELECT statements; use sql for writes and transactions";

/// Runs one SQL statement, outside or inside a transaction.
pub fn sql<S>(
    query: &str,
    params: &[Value],
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<SqlResult>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    execute(query, params, transaction_id, database_schema, false)
}

/// Runs one `SELECT` statement, outside or inside a transaction.
pub fn sql_query<S>(
    query: &str,
    params: &[Value],
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<SqlResult>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    execute(query, params, transaction_id, database_schema, true)
}

/// The access a statement requires beyond transaction ownership.
enum Access<'a> {
    /// `permission` on every listed table.
    Tables(AclPermission, Vec<&'a str>),
    /// At least one grant of any kind (`BEGIN`).
    AnyGrant,
    /// Nothing more (`COMMIT`, `ROLLBACK`).
    OwnerOnly,
}

fn execute<S>(
    query: &str,
    params: &[Value],
    transaction_id: Option<TransactionId>,
    database_schema: S,
    read_only: bool,
) -> IcDbmsResult<SqlResult>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    let statement = wasm_dbms_sql::parse(query)?.statement;
    if read_only && !matches!(statement, Statement::Select(_)) {
        return Err(SqlError::Unsupported(SQL_QUERY_READ_ONLY.to_string()).into());
    }
    if let Some(table) = statement_tables(&statement)
        .into_iter()
        .find(|table| table.starts_with(RESERVED_TABLE_PREFIX))
    {
        return Err(SqlError::UnknownTable(table.to_string()).into());
    }
    let access = required_access(&database_schema, &statement);

    DBMS_CONTEXT.with(|ctx| {
        let schema = CanisterSchema::new(database_schema);
        {
            let db = match transaction_id {
                Some(id) => WasmDbmsDatabase::from_transaction(ctx, schema.clone(), id),
                None => WasmDbmsDatabase::oneshot(ctx, schema.clone()),
            };
            authorize(&db, caller, &access)?;
        }
        let result = SqlEngine::new(schema).execute(ctx, transaction_id, query, params);
        track_ownership(caller, &statement, transaction_id, &result);
        result.map_err(IcDbmsError::from)
    })
}

/// Returns the tables named by `FROM`, `JOIN`, `INSERT INTO`, `UPDATE` or
/// `DELETE FROM`, each once, in source order. Aliases are ignored.
fn statement_tables(statement: &Statement) -> Vec<&str> {
    match statement {
        Statement::Select(select) => {
            let mut tables = vec![select.from.name.as_str()];
            for join in &select.joins {
                let table = join.table.name.as_str();
                if !tables.contains(&table) {
                    tables.push(table);
                }
            }
            tables
        }
        Statement::Insert(insert) => vec![insert.table.as_str()],
        Statement::Update(update) => vec![update.table.as_str()],
        Statement::Delete(delete) => vec![delete.table.as_str()],
        Statement::Begin | Statement::Commit | Statement::Rollback => Vec::new(),
    }
}

/// Maps `statement` to the access the typed endpoints would require for the
/// same operation.
fn required_access<'a, S>(schema: &S, statement: &'a Statement) -> Access<'a>
where
    S: DatabaseSchema<IcMemoryProvider>,
{
    match statement {
        Statement::Select(_) => Access::Tables(AclPermission::Read, statement_tables(statement)),
        Statement::Insert(_) => Access::Tables(AclPermission::Insert, statement_tables(statement)),
        Statement::Update(_) => Access::Tables(AclPermission::Update, statement_tables(statement)),
        Statement::Delete(delete) => {
            let behaviour = if delete.cascade {
                DeleteBehavior::Cascade
            } else {
                DeleteBehavior::Restrict
            };
            // An unknown table is checked by name, so a caller without an
            // all-tables grant gets `AccessDenied` instead of learning that
            // the table does not exist.
            let tables: Vec<&'a str> = match schema.static_table_name(&delete.table) {
                Ok(table) => delete_tables(schema, table, &behaviour),
                Err(_) => vec![delete.table.as_str()],
            };
            Access::Tables(AclPermission::Delete, tables)
        }
        Statement::Begin => Access::AnyGrant,
        Statement::Commit | Statement::Rollback => Access::OwnerOnly,
    }
}

fn authorize(
    db: &WasmDbmsDatabase<'_, IcMemoryProvider>,
    caller: Principal,
    access: &Access<'_>,
) -> IcDbmsResult<()> {
    match access {
        Access::Tables(permission, tables) => acl::require(db, caller, *permission, tables),
        Access::AnyGrant => acl::require_any_grant(db, caller),
        Access::OwnerOnly => Ok(()),
    }
}

/// Records the owner of a transaction opened by `BEGIN` and forgets the
/// transaction closed by `COMMIT` or `ROLLBACK`, whether or not closing it
/// succeeded, as the typed `commit` and `rollback` helpers do.
fn track_ownership(
    caller: Principal,
    statement: &Statement,
    transaction_id: Option<TransactionId>,
    result: &Result<SqlResult, SqlError>,
) {
    if let Ok(SqlResult::TxBegin(id)) = result {
        transaction::record(*id, caller);
    }
    if matches!(statement, Statement::Commit | Statement::Rollback)
        && let Some(id) = transaction_id
    {
        transaction::forget(&id);
    }
}

#[cfg(test)]
mod tests {

    use candid::Principal;
    use ic_dbms_api::prelude::{
        AclError, AclGrant, AclPermission, AclRequirement, IcDbmsError, SqlError, SqlRow,
    };
    use wasm_dbms::prelude::WasmDbmsDatabase;

    use super::*;
    use crate::api::{acl_list, begin_transaction, commit, init_acl};
    use crate::memory::DBMS_CONTEXT;
    use crate::schema::CanisterSchema;
    use crate::tests::{TestDatabaseSchema, load_fixtures};
    use crate::{acl, transaction};

    fn alice() -> Principal {
        crate::utils::caller()
    }

    fn bob() -> Principal {
        Principal::from_text("ryjl3-tyaaa-aaaaa-aaaba-cai").unwrap()
    }

    /// Loads the fixtures and makes alice, the test caller, an admin.
    fn setup_admin() {
        load_fixtures();
        init_acl(vec![alice()], TestDatabaseSchema).expect("bootstrap acl");
    }

    /// Loads the fixtures and makes bob the only admin: alice holds nothing.
    fn setup_unprivileged() {
        load_fixtures();
        init_acl(vec![bob()], TestDatabaseSchema).expect("bootstrap acl");
    }

    /// Grants alice `permission` on `table`, or on every table when `None`.
    fn grant_alice(permission: AclPermission, table: Option<&str>) {
        let grant = match table {
            Some(table) => AclGrant::table(alice(), permission, table),
            None => AclGrant::all_tables(alice(), permission),
        };
        DBMS_CONTEXT.with(|ctx| {
            let db = WasmDbmsDatabase::oneshot(ctx, CanisterSchema::new(TestDatabaseSchema));
            acl::grant(&db, &grant, |_| true).expect("grant");
        });
    }

    fn run(query: &str, params: &[Value], tx: Option<TransactionId>) -> IcDbmsResult<SqlResult> {
        sql(query, params, tx, TestDatabaseSchema)
    }

    fn rows(result: IcDbmsResult<SqlResult>) -> Vec<SqlRow> {
        match result.expect("sql failed") {
            SqlResult::Rows(rows) => rows,
            other => panic!("expected rows, got {other:?}"),
        }
    }

    fn values(row: &SqlRow) -> Vec<Value> {
        row.iter().map(|(_, value)| value.clone()).collect()
    }

    /// Number of users with id 100, read outside any transaction.
    fn count_user_100() -> usize {
        rows(run("SELECT id FROM users WHERE id = 100", &[], None)).len()
    }

    fn assert_denied(result: IcDbmsResult<SqlResult>, permission: AclPermission, table: &str) {
        match result {
            Err(IcDbmsError::Acl(AclError::AccessDenied {
                required,
                table: denied,
            })) => {
                assert_eq!(required, AclRequirement::Permission(permission));
                assert_eq!(denied.as_deref(), Some(table));
            }
            other => panic!("expected access denied on {table}, got {other:?}"),
        }
    }

    const INSERT_USER_100: &str =
        "INSERT INTO users (id, name, email, age) VALUES (100, 'Zed', 'zed@example.com', 30)";

    #[test]
    fn test_should_require_read_on_every_selected_table() {
        setup_unprivileged();
        grant_alice(AclPermission::Read, Some("posts"));
        let join = "SELECT posts.title, users.name FROM posts \
                    JOIN users ON posts.user = users.id WHERE posts.id = 0";

        assert_denied(run(join, &[], None), AclPermission::Read, "users");

        grant_alice(AclPermission::Read, Some("users"));
        let rows = rows(run(join, &[], None));
        assert_eq!(rows.len(), 1);
        assert_eq!(
            values(&rows[0]),
            vec![Value::from("First Post"), Value::from("Alice")]
        );
    }

    #[test]
    fn test_should_require_write_permission_per_statement() {
        setup_unprivileged();
        grant_alice(AclPermission::Read, None);
        let update = "UPDATE users SET name = 'Bobby' WHERE id = 1";
        let delete = "DELETE FROM posts WHERE id = 0";

        assert_denied(
            run(INSERT_USER_100, &[], None),
            AclPermission::Insert,
            "users",
        );
        assert_denied(run(update, &[], None), AclPermission::Update, "users");
        assert_denied(run(delete, &[], None), AclPermission::Delete, "posts");
        assert_eq!(count_user_100(), 0);

        grant_alice(AclPermission::Insert, Some("users"));
        grant_alice(AclPermission::Update, Some("users"));
        grant_alice(AclPermission::Delete, Some("posts"));
        assert_eq!(
            run(INSERT_USER_100, &[], None).expect("insert"),
            SqlResult::RowsAffected(1)
        );
        assert_eq!(
            run(update, &[], None).expect("update"),
            SqlResult::RowsAffected(1)
        );
        assert_eq!(
            run(delete, &[], None).expect("delete"),
            SqlResult::RowsAffected(1)
        );
    }

    #[test]
    fn test_should_require_delete_on_referencing_tables_for_cascade() {
        setup_unprivileged();
        grant_alice(AclPermission::Delete, Some("users"));
        let cascade = "DELETE FROM users WHERE id = 100 CASCADE";

        match run(cascade, &[], None) {
            Err(IcDbmsError::Acl(AclError::AccessDenied { required, table })) => {
                assert_eq!(required, AclRequirement::Permission(AclPermission::Delete));
                assert!(
                    matches!(table.as_deref(), Some("posts" | "messages")),
                    "unexpected table {table:?}"
                );
            }
            other => panic!("expected access denied, got {other:?}"),
        }
        // RESTRICT (the default) only touches `users`.
        assert_eq!(
            run("DELETE FROM users WHERE id = 100", &[], None).expect("restrict"),
            SqlResult::RowsAffected(0)
        );

        grant_alice(AclPermission::Delete, Some("posts"));
        grant_alice(AclPermission::Delete, Some("messages"));
        assert_eq!(
            run(cascade, &[], None).expect("cascade"),
            SqlResult::RowsAffected(0)
        );
    }

    #[test]
    fn test_should_hide_reserved_tables_from_sql() {
        setup_admin();
        let statements = [
            "SELECT * FROM ic_dbms_acl",
            "SELECT * FROM ic_dbms_acl AS users",
            "SELECT users.name FROM users JOIN ic_dbms_acl ON users.id = ic_dbms_acl.id",
            "INSERT INTO ic_dbms_acl (id) VALUES (1)",
            "UPDATE ic_dbms_acl SET table = NULL WHERE id = 0",
            "DELETE FROM ic_dbms_acl WHERE id = 0",
        ];
        for statement in statements {
            match run(statement, &[], None) {
                Err(IcDbmsError::Sql(SqlError::UnknownTable(table))) => {
                    assert_eq!(table, "ic_dbms_acl", "statement: {statement}");
                }
                other => panic!("expected unknown table for `{statement}`, got {other:?}"),
            }
        }
        assert!(matches!(
            sql_query("SELECT * FROM ic_dbms_acl", &[], None, TestDatabaseSchema),
            Err(IcDbmsError::Sql(SqlError::UnknownTable(_)))
        ));
        assert_eq!(
            acl_list(TestDatabaseSchema).expect("list"),
            vec![AclGrant::admin(alice())]
        );
    }

    #[test]
    fn test_should_track_transaction_ownership_through_sql() {
        setup_admin();
        let SqlResult::TxBegin(tx) = run("begin", &[], None).expect("begin") else {
            panic!("BEGIN must return TxBegin");
        };
        assert_eq!(transaction::owner(&tx), Some(alice()));

        run(INSERT_USER_100, &[], Some(tx)).expect("insert in tx");
        assert_eq!(count_user_100(), 0);
        let in_tx = sql_query(
            "SELECT id FROM users WHERE id = 100",
            &[],
            Some(tx),
            TestDatabaseSchema,
        );
        assert_eq!(rows(in_tx).len(), 1);

        assert_eq!(
            run("COMMIT;", &[], Some(tx)).expect("commit"),
            SqlResult::TxCommit
        );
        assert_eq!(transaction::owner(&tx), None);
        assert_eq!(count_user_100(), 1);
    }

    #[test]
    fn test_should_forget_rolled_back_transaction() {
        setup_admin();
        let SqlResult::TxBegin(tx) = run("BEGIN TRANSACTION", &[], None).expect("begin") else {
            panic!("BEGIN must return TxBegin");
        };
        run(INSERT_USER_100, &[], Some(tx)).expect("insert in tx");
        assert_eq!(
            run("rollback", &[], Some(tx)).expect("rollback"),
            SqlResult::TxRollback
        );
        assert_eq!(transaction::owner(&tx), None);
        assert_eq!(count_user_100(), 0);
    }

    #[test]
    fn test_should_commit_typed_transaction_through_sql() {
        setup_admin();
        let tx = begin_transaction(TestDatabaseSchema).expect("begin");
        run(INSERT_USER_100, &[], Some(tx)).expect("insert in tx");
        commit(tx, TestDatabaseSchema).expect("typed commit");
        assert_eq!(count_user_100(), 1);
    }

    #[test]
    fn test_should_require_any_grant_to_begin() {
        setup_unprivileged();
        assert!(matches!(
            run("BEGIN", &[], None),
            Err(IcDbmsError::Acl(AclError::AccessDenied {
                required: AclRequirement::AnyGrant,
                table: None,
            }))
        ));
        assert_eq!(transaction::len(), 0);
    }

    #[test]
    #[should_panic(expected = "does not own transaction")]
    fn test_should_trap_on_foreign_transaction_in_sql() {
        setup_admin();
        let tx = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());
        transaction::record(tx, bob());
        let _ = run("COMMIT", &[], Some(tx));
    }

    #[test]
    #[should_panic(expected = "does not own transaction")]
    fn test_should_trap_on_foreign_transaction_in_sql_query() {
        setup_admin();
        let tx = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());
        transaction::record(tx, bob());
        let _ = sql_query("SELECT * FROM users", &[], Some(tx), TestDatabaseSchema);
    }

    #[test]
    fn test_should_reject_non_select_in_sql_query() {
        setup_admin();
        let statements = [
            INSERT_USER_100,
            "UPDATE users SET name = 'Bobby' WHERE id = 1",
            "DELETE FROM posts WHERE id = 0",
            "BEGIN",
            "COMMIT",
            "ROLLBACK",
        ];
        for statement in statements {
            match sql_query(statement, &[], None, TestDatabaseSchema) {
                Err(IcDbmsError::Sql(SqlError::Unsupported(message))) => {
                    assert_eq!(message, SQL_QUERY_READ_ONLY, "statement: {statement}");
                }
                other => panic!("expected unsupported for `{statement}`, got {other:?}"),
            }
        }
        assert_eq!(count_user_100(), 0);
        assert_eq!(transaction::len(), 0);
        let read = sql_query(
            "SELECT name FROM users WHERE id = ?",
            &[Value::from(1u32)],
            None,
            TestDatabaseSchema,
        );
        assert_eq!(values(&rows(read)[0]), vec![Value::from("Bob")]);
    }

    #[test]
    fn test_should_wrap_sql_errors() {
        setup_admin();
        assert!(matches!(
            run("SELEC * FROM users", &[], None),
            Err(IcDbmsError::Sql(SqlError::Parse { .. }))
        ));
        assert!(matches!(
            run("SELECT * FROM ghosts", &[], None),
            Err(IcDbmsError::Sql(SqlError::UnknownTable(table))) if table == "ghosts"
        ));
    }

    #[test]
    fn test_should_not_reveal_unknown_tables_to_unprivileged_callers() {
        setup_unprivileged();
        grant_alice(AclPermission::Read, Some("users"));
        assert_denied(
            run("SELECT * FROM ghosts", &[], None),
            AclPermission::Read,
            "ghosts",
        );
    }
}
