//! Generic per-operation helpers consumed by the endpoints generated by
//! `#[derive(DbmsCanister)]`.
//!
//! Every helper receives the user's schema `S`, wraps it in
//! [`CanisterSchema`] so the engine sees the reserved tables too, and checks
//! the caller against the ACL through the same database it then operates on.

mod inspect;

use candid::Principal;
use ic_dbms_api::prelude::{
    AclGrant, AclPermission, AggregateFunction, AggregatedRow, ColumnDef, Database, DeleteBehavior,
    Filter, IcDbmsError, IcDbmsResult, InsertRecord, JoinColumnDef, MigrationOp, MigrationPolicy,
    Query, TableSchema, TransactionId, UpdateRecord, Value,
};
use wasm_dbms::prelude::{DatabaseSchema, WasmDbmsDatabase};

pub use self::inspect::inspect;
use crate::memory::{DBMS_CONTEXT, IcMemoryProvider};
use crate::schema::CanisterSchema;
use crate::{acl, transaction, trap};

/// Registers the reserved ACL table and grants [`ic_dbms_api::prelude::AclPermission::Admin`] to
/// every
/// principal in `principals`. Called by the generated `init` after the user
/// tables are registered.
pub fn init_acl<S>(principals: Vec<Principal>, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    DBMS_CONTEXT.with(acl::register)?;
    with_database(None, database_schema, |db| {
        for principal in principals {
            acl::grant(db, &AclGrant::admin(principal), |_| false)?;
        }
        Ok(())
    })
}

/// Stores `grant`. Caller must hold [`ic_dbms_api::prelude::AclPermission::Admin`]. The table it
/// names must be one of the user's tables.
pub fn acl_grant<S>(grant: AclGrant, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    let user_tables: Vec<String> = database_schema
        .compiled_snapshots_dyn()
        .into_iter()
        .map(|snapshot| snapshot.name)
        .collect();
    with_database(None, database_schema, |db| {
        acl::require_admin(db, caller)?;
        acl::grant(db, &grant, |table| user_tables.iter().any(|t| t == table))
    })
}

/// Removes `grant`. Caller must hold [`ic_dbms_api::prelude::AclPermission::Admin`]. Refuses to
/// remove the last admin grant.
pub fn acl_revoke<S>(grant: AclGrant, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        acl::require_admin(db, caller)?;
        acl::revoke(db, &grant)
    })
}

/// Lists every grant. Caller must hold [`ic_dbms_api::prelude::AclPermission::Admin`].
pub fn acl_list<S>(database_schema: S) -> IcDbmsResult<Vec<AclGrant>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        acl::require_admin(db, caller)?;
        acl::list(db)
    })
}

/// Returns the caller's own grants. Always permitted.
pub fn my_permissions<S>(database_schema: S) -> IcDbmsResult<Vec<AclGrant>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| acl::grants_of(db, caller))
}

/// Begins a new transaction owned by the caller and returns its ID. Caller
/// must hold at least one grant.
pub fn begin_transaction<S>(database_schema: S) -> IcDbmsResult<TransactionId>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        acl::require_any_grant(db, caller)
    })?;
    let transaction_id = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());
    transaction::record(transaction_id, caller);
    Ok(transaction_id)
}

/// Commits the transaction with the given ID. Caller must own the
/// transaction.
///
/// Traps when the ID is unknown, already closed, or owned by another
/// principal. The ownership entry is removed whether or not the engine call
/// succeeds, because the engine consumes the transaction either way.
pub fn commit<S>(transaction_id: TransactionId, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_caller_owns_transaction(Some(&transaction_id));
    let result = DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::from_transaction(
            ctx,
            CanisterSchema::new(database_schema),
            transaction_id,
        );
        db.commit().map_err(IcDbmsError::from)
    });
    transaction::forget(&transaction_id);
    result
}

/// Rolls back the transaction with the given ID. Caller must own the
/// transaction.
///
/// Traps when the ID is unknown, already closed, or owned by another
/// principal. The ownership entry is removed whether or not the engine call
/// succeeds.
pub fn rollback<S>(transaction_id: TransactionId, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_caller_owns_transaction(Some(&transaction_id));
    let result = DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::from_transaction(
            ctx,
            CanisterSchema::new(database_schema),
            transaction_id,
        );
        db.rollback().map_err(IcDbmsError::from)
    });
    transaction::forget(&transaction_id);
    result
}

/// Selects typed records from table `T`, optionally inside a transaction.
/// Caller must hold [`AclPermission::Read`] on `T` and on every eagerly loaded
/// relation. Traps when `transaction_id` names a transaction the caller did
/// not open.
pub fn select<T, S>(
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<T::Record>>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require(
            db,
            caller,
            AclPermission::Read,
            &read_tables(T::table_name(), &query),
        )?;
        db.select::<T>(query).map_err(IcDbmsError::from)
    })
}

/// Selects untyped rows from the table called `table`, optionally inside a
/// transaction. Caller must hold [`AclPermission::Read`] on `table` and on
/// every eagerly loaded relation; reading a reserved table requires
/// [`AclPermission::Admin`]. Traps when `transaction_id` names a transaction
/// the caller did not open.
pub fn select_raw<S>(
    table: &str,
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<Vec<(ColumnDef, Value)>>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require(db, caller, AclPermission::Read, &read_tables(table, &query))?;
        db.select_raw(table, query).map_err(IcDbmsError::from)
    })
}

/// Runs a query with joins rooted at `table`, optionally inside a
/// transaction. Caller must hold [`AclPermission::Read`] on `table`, on every
/// joined table and on every eagerly loaded relation. Traps when
/// `transaction_id` names a transaction the caller did not open.
pub fn select_join<S>(
    table: &str,
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<Vec<(JoinColumnDef, Value)>>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require(db, caller, AclPermission::Read, &read_tables(table, &query))?;
        db.select_join(table, query).map_err(IcDbmsError::from)
    })
}

/// Runs an aggregate query on table `T`, optionally inside a transaction.
/// Caller must hold [`AclPermission::Read`] on `T`. Traps when `transaction_id`
/// names a transaction the caller did not open.
pub fn aggregate<T, S>(
    query: Query,
    aggregates: Vec<AggregateFunction>,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<AggregatedRow>>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require(
            db,
            caller,
            AclPermission::Read,
            &read_tables(T::table_name(), &query),
        )?;
        db.aggregate::<T>(query, &aggregates)
            .map_err(IcDbmsError::from)
    })
}

/// Inserts a record into table `T`, optionally inside a transaction. Caller
/// must hold [`AclPermission::Insert`] on `T`. Traps when `transaction_id` names a
/// transaction the caller did not open.
pub fn insert<T, S>(
    record: T::Insert,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<()>
where
    T: TableSchema,
    T::Insert: InsertRecord<Schema = T>,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require(db, caller, AclPermission::Insert, &[T::table_name()])?;
        db.insert::<T>(record).map_err(IcDbmsError::from)
    })
}

/// Updates records of table `T`, optionally inside a transaction. Returns
/// the number of updated rows. Caller must hold [`AclPermission::Update`] on
/// `T`. Traps
/// when `transaction_id` names a transaction the caller did not open.
pub fn update<T, S>(
    patch: T::Update,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<u64>
where
    T: TableSchema,
    T::Update: UpdateRecord<Schema = T>,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require(db, caller, AclPermission::Update, &[T::table_name()])?;
        db.update::<T>(patch).map_err(IcDbmsError::from)
    })
}

/// Deletes records of table `T`, optionally inside a transaction. Returns
/// the number of deleted rows. Caller must hold [`AclPermission::Delete`] on
/// `T` and, with [`DeleteBehavior::Cascade`], on every table that references
/// `T`. Traps when `transaction_id` names a transaction the caller did not
/// open.
pub fn delete<T, S>(
    behaviour: DeleteBehavior,
    filter: Option<Filter>,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<u64>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_caller_owns_transaction(transaction_id.as_ref());
    let tables = delete_tables(&database_schema, T::table_name(), &behaviour);
    with_database(transaction_id, database_schema, |db| {
        acl::require(db, caller, AclPermission::Delete, &tables)?;
        db.delete::<T>(behaviour, filter).map_err(IcDbmsError::from)
    })
}

/// Returns whether the persisted schema differs from the compiled one.
/// Caller must hold [`AclPermission::Admin`] or be a controller.
pub fn has_drift<S>(database_schema: S) -> IcDbmsResult<bool>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        authorize_migration(db, caller)?;
        db.has_drift().map_err(IcDbmsError::from)
    })
}

/// Returns the migration operations needed to heal schema drift. Caller must
/// hold [`AclPermission::Admin`] or be a controller.
pub fn pending_migrations<S>(database_schema: S) -> IcDbmsResult<Vec<MigrationOp>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        authorize_migration(db, caller)?;
        db.pending_migrations().map_err(IcDbmsError::from)
    })
}

/// Applies the pending migrations under `policy`. Caller must hold
/// [`AclPermission::Admin`] or be a controller.
pub fn migrate<S>(policy: MigrationPolicy, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::oneshot(ctx, CanisterSchema::new(database_schema));
        authorize_migration(&db, caller)?;
        db.migrate(policy).map_err(IcDbmsError::from)
    })
}

/// Clears the transaction ownership ledger. Called by the generated
/// `pre_upgrade` hook.
///
/// The heap is discarded on upgrade anyway, so this only makes the intent
/// explicit: open transactions and their owners do not survive an upgrade.
pub fn pre_upgrade() {
    transaction::clear();
}

/// Returns the tables a read of `table` with `query` touches: the root
/// table, every joined table and every eagerly loaded relation, each once.
fn read_tables<'a>(table: &'a str, query: &'a Query) -> Vec<&'a str> {
    let mut tables = vec![table];
    let others = query
        .joins
        .iter()
        .map(|join| join.table.as_str())
        .chain(query.eager_relations.iter().map(String::as_str));
    for other in others {
        if !tables.contains(&other) {
            tables.push(other);
        }
    }
    tables
}

/// Returns the tables a delete on `table` removes rows from: `table` itself
/// and, under [`DeleteBehavior::Cascade`], every table that references it
/// directly or transitively.
fn delete_tables<S>(
    schema: &S,
    table: &'static str,
    behaviour: &DeleteBehavior,
) -> Vec<&'static str>
where
    S: DatabaseSchema<IcMemoryProvider>,
{
    let mut tables = vec![table];
    if !matches!(behaviour, DeleteBehavior::Cascade) {
        return tables;
    }
    let mut next = 0;
    while next < tables.len() {
        let referencing = schema.referenced_tables(tables[next]);
        for (referencing_table, _) in referencing {
            if !tables.contains(&referencing_table) {
                tables.push(referencing_table);
            }
        }
        next += 1;
    }
    tables
}

/// Controllers may always run migrations: while the schema has drifted the
/// ACL table cannot be read, and controllers already hold full power over the
/// canister. Everyone else must hold [`AclPermission::Admin`].
fn authorize_migration(
    db: &WasmDbmsDatabase<'_, IcMemoryProvider>,
    caller: Principal,
) -> IcDbmsResult<()> {
    if crate::utils::is_controller(caller) {
        return Ok(());
    }
    acl::require_admin(db, caller)
}

/// Closure-based helper that creates a [`WasmDbmsDatabase`] over the composed
/// [`CanisterSchema`] inside the `DBMS_CONTEXT` thread-local and invokes `f`
/// on it.
fn with_database<S, F, R>(transaction_id: Option<TransactionId>, database_schema: S, f: F) -> R
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
    F: for<'a> FnOnce(&WasmDbmsDatabase<'a, IcMemoryProvider>) -> R,
{
    DBMS_CONTEXT.with(|ctx| {
        let schema = CanisterSchema::new(database_schema);
        let db = match transaction_id {
            Some(tx_id) => WasmDbmsDatabase::from_transaction(ctx, schema, tx_id),
            None => WasmDbmsDatabase::oneshot(ctx, schema),
        };
        f(&db)
    })
}

/// Traps unless `transaction_id` is `None` or names an open transaction
/// that the caller opened.
///
/// A mismatch is reported exactly like an unknown ID, so a caller cannot
/// learn whether somebody else's transaction exists. An ID the engine has
/// already closed is evicted from the ledger before trapping.
fn assert_caller_owns_transaction(transaction_id: Option<&TransactionId>) {
    let Some(tx_id) = transaction_id else {
        return;
    };
    let caller = crate::utils::caller();
    if !DBMS_CONTEXT.with(|ctx| ctx.has_transaction(tx_id)) {
        transaction::forget(tx_id);
        trap!("Caller {caller} does not own transaction {tx_id}");
    }
    if transaction::owner(tx_id) != Some(caller) {
        trap!("Caller {caller} does not own transaction {tx_id}");
    }
}

#[cfg(test)]
mod tests {

    use ic_dbms_api::prelude::{AclError, AclGrant, AclPermission, AclRequirement, Uint32};

    use super::*;
    use crate::tests::{TestDatabaseSchema, UserInsertRequest, load_fixtures};

    fn alice() -> Principal {
        crate::utils::caller()
    }

    fn bob() -> Principal {
        Principal::from_text("ryjl3-tyaaa-aaaaa-aaaba-cai").unwrap()
    }

    /// Registers the test tables and bootstraps alice as admin.
    fn bootstrap_alice() {
        DBMS_CONTEXT.with(|ctx| {
            TestDatabaseSchema::register_tables(ctx).expect("failed to register tables");
        });
        init_acl(vec![alice()], TestDatabaseSchema).expect("bootstrap acl");
    }

    fn user(id: u32) -> UserInsertRequest {
        UserInsertRequest {
            id: id.into(),
            name: "Alice".to_string().into(),
            email: "alice@example.com".into(),
            age: 25u32.into(),
        }
    }

    fn assert_denied<T: std::fmt::Debug>(
        res: IcDbmsResult<T>,
        permission: AclPermission,
        table: Option<&str>,
    ) {
        match res {
            Err(IcDbmsError::Acl(AclError::AccessDenied {
                required,
                table: denied_table,
            })) => {
                assert_eq!(required, AclRequirement::Permission(permission));
                assert_eq!(denied_table.as_deref(), table);
            }
            other => panic!("expected access denied, got {other:?}"),
        }
    }

    #[test]
    fn test_init_acl_bootstraps_admins() {
        bootstrap_alice();
        let entries = acl_list(TestDatabaseSchema).expect("list");
        assert_eq!(entries, vec![AclGrant::admin(alice())]);
        assert_eq!(
            my_permissions(TestDatabaseSchema).expect("perms"),
            vec![AclGrant::admin(alice())]
        );
    }

    #[test]
    fn test_init_acl_rejects_anonymous_admin() {
        DBMS_CONTEXT.with(|ctx| {
            TestDatabaseSchema::register_tables(ctx).expect("failed to register tables");
        });
        let err = init_acl(vec![Principal::anonymous()], TestDatabaseSchema)
            .expect_err("anonymous admin");
        assert!(matches!(
            err,
            IcDbmsError::Acl(AclError::AnonymousPrincipal)
        ));
    }

    #[test]
    fn test_should_grant_and_revoke_admin() {
        bootstrap_alice();
        acl_grant(AclGrant::admin(bob()), TestDatabaseSchema).expect("grant");
        assert!(
            acl_list(TestDatabaseSchema)
                .unwrap()
                .iter()
                .any(|grant| grant == &AclGrant::admin(bob()))
        );
        acl_revoke(AclGrant::admin(bob()), TestDatabaseSchema).expect("revoke");
        assert!(
            !acl_list(TestDatabaseSchema)
                .unwrap()
                .iter()
                .any(|grant| grant == &AclGrant::admin(bob()))
        );
    }

    #[test]
    fn test_should_refuse_to_revoke_last_admin_through_api() {
        bootstrap_alice();
        let err = acl_revoke(AclGrant::admin(alice()), TestDatabaseSchema).expect_err("last");
        assert!(matches!(err, IcDbmsError::Acl(AclError::LastAdmin)));
    }

    #[test]
    fn test_unlisted_caller_is_denied_everywhere() {
        DBMS_CONTEXT.with(|ctx| {
            TestDatabaseSchema::register_tables(ctx).expect("failed to register tables");
        });
        init_acl(vec![bob()], TestDatabaseSchema).expect("bootstrap bob");

        assert_denied(
            insert::<crate::tests::User, _>(user(1), None, TestDatabaseSchema),
            AclPermission::Insert,
            Some("users"),
        );
        assert_denied(
            select::<crate::tests::User, _>(
                Query::builder().all().build(),
                None,
                TestDatabaseSchema,
            ),
            AclPermission::Read,
            Some("users"),
        );
        assert_denied(
            select_raw(
                "users",
                Query::builder().all().build(),
                None,
                TestDatabaseSchema,
            ),
            AclPermission::Read,
            Some("users"),
        );
        assert_denied(
            select_raw(
                "ic_dbms_acl",
                Query::builder().all().build(),
                None,
                TestDatabaseSchema,
            ),
            AclPermission::Admin,
            Some("ic_dbms_acl"),
        );
        assert!(matches!(
            begin_transaction(TestDatabaseSchema),
            Err(IcDbmsError::Acl(AclError::AccessDenied {
                required: AclRequirement::AnyGrant,
                table: None,
            }))
        ));
        assert_denied(
            acl_grant(AclGrant::admin(alice()), TestDatabaseSchema),
            AclPermission::Admin,
            None,
        );
        assert_denied(acl_list(TestDatabaseSchema), AclPermission::Admin, None);
        assert_denied(has_drift(TestDatabaseSchema), AclPermission::Admin, None);
        assert_denied(
            migrate(MigrationPolicy::default(), TestDatabaseSchema),
            AclPermission::Admin,
            None,
        );
        assert!(my_permissions(TestDatabaseSchema).unwrap().is_empty());
    }

    #[test]
    fn test_admin_can_read_reserved_acl_table_through_select_raw() {
        bootstrap_alice();
        let rows = select_raw(
            "ic_dbms_acl",
            Query::builder().all().build(),
            None,
            TestDatabaseSchema,
        )
        .expect("select acl");
        assert_eq!(rows.len(), 1);
    }

    #[test]
    fn test_should_begin_transaction() {
        bootstrap_alice();
        let _tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
    }

    #[test]
    fn test_should_commit_transaction() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        let res = commit(tx_id, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_rollback_transaction() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        let res = rollback(tx_id, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_insert_inside_transaction_and_commit() {
        load_fixtures();
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        insert::<crate::tests::User, _>(user(100), Some(tx_id), TestDatabaseSchema)
            .expect("insert in tx");
        commit(tx_id, TestDatabaseSchema).expect("commit");
        let rows = select::<crate::tests::User, _>(
            Query::builder()
                .all()
                .and_where(Filter::Eq("id".to_string(), Uint32::from(100u32).into()))
                .build(),
            None,
            TestDatabaseSchema,
        )
        .expect("select");
        assert_eq!(rows.len(), 1);
    }

    #[test]
    fn test_should_insert_record() {
        load_fixtures();
        bootstrap_alice();
        let res = insert::<crate::tests::User, _>(user(100), None, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_select_record() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder().all().limit(10).build();
        let res = select::<crate::tests::User, _>(query, None, TestDatabaseSchema);
        assert!(res.is_ok());
        let records = res.unwrap();
        assert!(!records.is_empty());
    }

    #[test]
    fn test_should_update_record() {
        load_fixtures();
        bootstrap_alice();

        let patch = crate::tests::UserUpdateRequest {
            id: None,
            name: Some("Robert".into()),
            email: Some("robert@example.com".into()),
            age: None,
            where_clause: Some(Filter::Eq("id".to_string(), Uint32::from(1u32).into())),
        };
        let res = update::<crate::tests::User, _>(patch, None, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_delete_record() {
        load_fixtures();
        bootstrap_alice();

        let filter = Some(Filter::Eq("id".to_string(), Uint32::from(2u32).into()));
        let res = delete::<crate::tests::User, _>(
            DeleteBehavior::Cascade,
            filter,
            None,
            TestDatabaseSchema,
        );
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_aggregate() {
        load_fixtures();
        bootstrap_alice();
        let res = aggregate::<crate::tests::User, _>(
            Query::builder().all().build(),
            vec![AggregateFunction::Count(None)],
            None,
            TestDatabaseSchema,
        );
        assert!(res.is_ok());
        assert_eq!(res.unwrap().len(), 1);
    }

    #[test]
    fn test_should_select_raw_record() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder().all().limit(10).build();
        let res = select_raw("users", query, None, TestDatabaseSchema);
        assert!(res.is_ok());
        let rows = res.unwrap();
        assert!(!rows.is_empty());
        for row in &rows {
            assert!(row.iter().any(|(col, _)| col.name == "id"));
            assert!(row.iter().any(|(col, _)| col.name == "name"));
        }
    }

    #[test]
    fn test_should_fail_select_raw_unknown_table() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder().all().build();
        let res = select_raw("nonexistent", query, None, TestDatabaseSchema);
        assert!(res.is_err());
    }

    #[test]
    fn test_should_select_join() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder()
            .all()
            .inner_join("posts", "users.id", "posts.user")
            .build();
        let res = select_join("users", query, None, TestDatabaseSchema);
        assert!(res.is_ok());
        assert!(!res.unwrap().is_empty());
    }

    #[test]
    fn test_migration_endpoints_report_no_drift_for_admin() {
        load_fixtures();
        bootstrap_alice();
        assert!(!has_drift(TestDatabaseSchema).expect("has_drift"));
        assert!(
            pending_migrations(TestDatabaseSchema)
                .expect("pending")
                .is_empty()
        );
        migrate(MigrationPolicy::default(), TestDatabaseSchema).expect("noop migrate");
    }

    #[test]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 1111"]
    fn test_should_trap_on_unknown_transaction() {
        load_fixtures();
        bootstrap_alice();
        let _ = commit(1111, TestDatabaseSchema);
    }

    #[test]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 0"]
    fn test_should_not_allow_operating_wrong_tx() {
        load_fixtures();
        bootstrap_alice();

        // bob opens a transaction through the engine and the ledger
        let tx_id = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());
        crate::transaction::record(tx_id, bob());

        // try to commit the transaction started by bob (we are alice)
        let _ = commit(tx_id, TestDatabaseSchema);
    }

    #[test]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 0"]
    fn test_should_not_allow_inserting_into_wrong_tx() {
        load_fixtures();
        bootstrap_alice();
        let tx_id = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());
        crate::transaction::record(tx_id, bob());
        let _ = insert::<crate::tests::User, _>(user(100), Some(tx_id), TestDatabaseSchema);
    }

    #[test]
    fn test_begin_records_caller_and_commit_forgets_it() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        assert_eq!(crate::transaction::owner(&tx_id), Some(alice()));
        commit(tx_id, TestDatabaseSchema).expect("commit");
        assert_eq!(crate::transaction::owner(&tx_id), None);
        assert_eq!(crate::transaction::len(), 0);
    }

    #[test]
    fn test_commit_forgets_owner_when_engine_returns_error() {
        load_fixtures();
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        let staged_patch = crate::tests::UserUpdateRequest {
            id: None,
            name: Some("staged".into()),
            email: None,
            age: None,
            where_clause: Some(Filter::Eq("id".to_string(), Uint32::from(0u32).into())),
        };
        update::<crate::tests::User, _>(staged_patch, Some(tx_id), TestDatabaseSchema)
            .expect("stage update");

        let concurrent_patch = crate::tests::UserUpdateRequest {
            id: None,
            name: Some("concurrent".into()),
            email: None,
            age: None,
            where_clause: Some(Filter::Eq("id".to_string(), Uint32::from(0u32).into())),
        };
        update::<crate::tests::User, _>(concurrent_patch, None, TestDatabaseSchema)
            .expect("update outside transaction");

        let result = commit(tx_id, TestDatabaseSchema);
        assert!(matches!(result, Err(IcDbmsError::Dbms(_))));
        assert_eq!(crate::transaction::owner(&tx_id), None);
        assert!(!DBMS_CONTEXT.with(|ctx| ctx.has_transaction(&tx_id)));
    }

    #[test]
    fn test_rollback_forgets_owner() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        rollback(tx_id, TestDatabaseSchema).expect("rollback");
        assert_eq!(crate::transaction::owner(&tx_id), None);
    }

    #[test]
    fn test_should_trap_and_evict_closed_transaction() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        commit(tx_id, TestDatabaseSchema).expect("commit");
        // Pretend the ledger missed the close.
        crate::transaction::record(tx_id, alice());
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            commit(tx_id, TestDatabaseSchema)
        }));
        assert!(result.is_err(), "closed transaction must trap");
        assert_eq!(
            crate::transaction::owner(&tx_id),
            None,
            "stale entry evicted"
        );
    }

    #[test]
    fn test_pre_upgrade_clears_ledger() {
        bootstrap_alice();
        let _tx = begin_transaction(TestDatabaseSchema).expect("begin");
        assert_eq!(crate::transaction::len(), 1);
        pre_upgrade();
        assert_eq!(crate::transaction::len(), 0);
    }

    #[test]
    fn test_read_tables_lists_root_joins_and_eager_relations_once() {
        let plain = Query::builder().all().build();
        assert_eq!(read_tables("users", &plain), vec!["users"]);

        let query = Query::builder()
            .all()
            .inner_join("posts", "users.id", "posts.user")
            .left_join("messages", "users.id", "messages.sender")
            .with("posts")
            .with("users")
            .build();
        assert_eq!(
            read_tables("users", &query),
            vec!["users", "posts", "messages"]
        );
    }

    #[test]
    fn test_delete_tables_follows_references_only_on_cascade() {
        assert_eq!(
            delete_tables(&TestDatabaseSchema, "users", &DeleteBehavior::Restrict),
            vec!["users"]
        );
        let mut cascade = delete_tables(&TestDatabaseSchema, "users", &DeleteBehavior::Cascade);
        cascade.sort_unstable();
        assert_eq!(cascade, vec!["messages", "posts", "users"]);
        assert_eq!(
            delete_tables(&TestDatabaseSchema, "posts", &DeleteBehavior::Cascade),
            vec!["posts"]
        );
    }
}
