//! Generic per-operation helpers consumed by the endpoints generated by
//! `#[derive(DbmsCanister)]`.

mod inspect;

use ic_dbms_api::prelude::{
    AggregateFunction, AggregatedRow, ColumnDef, Database, DeleteBehavior, Filter, IcDbmsResult,
    InsertRecord, JoinColumnDef, MigrationOp, MigrationPolicy, Query, TableSchema, TransactionId,
    UpdateRecord, Value,
};
use wasm_dbms::prelude::{DatabaseSchema, WasmDbmsDatabase};

pub use self::inspect::inspect;
use crate::memory::{DBMS_CONTEXT, IcMemoryProvider};
use crate::trap;

/// Begins a new transaction and returns its ID.
pub fn begin_transaction() -> TransactionId {
    DBMS_CONTEXT.with(|ctx| ctx.begin_transaction())
}

/// Commits the transaction with the given ID.
///
/// Traps when the ID does not name an open transaction.
pub fn commit<S>(transaction_id: TransactionId, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(Some(&transaction_id));
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::from_transaction(ctx, database_schema, transaction_id);
        db.commit()
    })
}

/// Rolls back the transaction with the given ID.
///
/// Traps when the ID does not name an open transaction.
pub fn rollback<S>(transaction_id: TransactionId, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(Some(&transaction_id));
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::from_transaction(ctx, database_schema, transaction_id);
        db.rollback()
    })
}

/// Selects typed records from table `T`, optionally inside a transaction.
pub fn select<T, S>(
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<T::Record>>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| db.select::<T>(query))
}

/// Selects untyped rows from the table called `table`, optionally inside a
/// transaction.
pub fn select_raw<S>(
    table: &str,
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<Vec<(ColumnDef, Value)>>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        db.select_raw(table, query)
    })
}

/// Runs a query with joins rooted at `table`, optionally inside a
/// transaction.
pub fn select_join<S>(
    table: &str,
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<Vec<(JoinColumnDef, Value)>>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        db.select_join(table, query)
    })
}

/// Runs an aggregate query on table `T`, optionally inside a transaction.
pub fn aggregate<T, S>(
    query: Query,
    aggregates: Vec<AggregateFunction>,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<AggregatedRow>>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        db.aggregate::<T>(query, &aggregates)
    })
}

/// Inserts a record into table `T`, optionally inside a transaction.
pub fn insert<T, S>(
    record: T::Insert,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<()>
where
    T: TableSchema,
    T::Insert: InsertRecord<Schema = T>,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| db.insert::<T>(record))
}

/// Updates records of table `T`, optionally inside a transaction. Returns
/// the number of updated rows.
pub fn update<T, S>(
    patch: T::Update,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<u64>
where
    T: TableSchema,
    T::Update: UpdateRecord<Schema = T>,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| db.update::<T>(patch))
}

/// Deletes records of table `T`, optionally inside a transaction. Returns
/// the number of deleted rows.
pub fn delete<T, S>(
    behaviour: DeleteBehavior,
    filter: Option<Filter>,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<u64>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        db.delete::<T>(behaviour, filter)
    })
}

/// Returns whether the persisted schema differs from the compiled one.
pub fn has_drift<S>(database_schema: S) -> IcDbmsResult<bool>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    with_database(None, database_schema, |db| db.has_drift())
}

/// Returns the migration operations needed to heal schema drift.
pub fn pending_migrations<S>(database_schema: S) -> IcDbmsResult<Vec<MigrationOp>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    with_database(None, database_schema, |db| db.pending_migrations())
}

/// Applies the pending migrations under `policy`.
pub fn migrate<S>(policy: MigrationPolicy, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::oneshot(ctx, database_schema);
        db.migrate(policy)
    })
}

/// Closure-based helper that creates a [`WasmDbmsDatabase`] inside the
/// `DBMS_CONTEXT` thread-local and invokes `f` on it.
fn with_database<S, F, R>(transaction_id: Option<TransactionId>, database_schema: S, f: F) -> R
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
    F: for<'a> FnOnce(&WasmDbmsDatabase<'a, IcMemoryProvider>) -> R,
{
    DBMS_CONTEXT.with(|ctx| {
        let db = match transaction_id {
            Some(tx_id) => WasmDbmsDatabase::from_transaction(ctx, database_schema, tx_id),
            None => WasmDbmsDatabase::oneshot(ctx, database_schema),
        };
        f(&db)
    })
}

/// Traps unless `transaction_id` is `None` or names an open transaction.
fn assert_transaction_is_open(transaction_id: Option<&TransactionId>) {
    let Some(tx_id) = transaction_id else {
        return;
    };
    let caller = crate::utils::caller();
    if !DBMS_CONTEXT.with(|ctx| ctx.has_transaction(tx_id)) {
        trap!("Caller {caller} does not own transaction {tx_id}");
    }
}

#[cfg(test)]
mod tests {

    use candid::Principal;
    use ic_dbms_api::prelude::Uint32;

    use super::*;
    use crate::tests::{UserInsertRequest, load_fixtures};

    fn init_schema() {
        DBMS_CONTEXT.with(|ctx| {
            crate::tests::TestDatabaseSchema::register_tables(ctx)
                .expect("failed to register tables");
        });
    }

    #[test]
    fn test_should_begin_transaction() {
        init_schema();
        let _tx_id = begin_transaction();
    }

    #[test]
    fn test_should_commit_transaction() {
        init_schema();
        let tx_id = begin_transaction();
        let res = commit(tx_id, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_rollback_transaction() {
        init_schema();
        let tx_id = begin_transaction();
        let res = rollback(tx_id, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_insert_record() {
        load_fixtures();
        let record = UserInsertRequest {
            id: 100u32.into(),
            name: "Alice".to_string().into(),
            email: "alice@example.com".into(),
            age: 25u32.into(),
        };

        let res = insert::<crate::tests::User, _>(record, None, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_select_record() {
        load_fixtures();
        let query = Query::builder().all().limit(10).build();
        let res = select::<crate::tests::User, _>(query, None, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
        let records = res.unwrap();
        assert!(!records.is_empty());
    }

    #[test]
    fn test_should_update_record() {
        load_fixtures();

        let patch = crate::tests::UserUpdateRequest {
            id: None,
            name: Some("Robert".into()),
            email: Some("robert@example.com".into()),
            age: None,
            where_clause: Some(Filter::Eq("id".to_string(), Uint32::from(1u32).into())),
        };
        let res = update::<crate::tests::User, _>(patch, None, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_delete_record() {
        load_fixtures();

        let filter = Some(Filter::Eq("id".to_string(), Uint32::from(2u32).into()));
        let res = delete::<crate::tests::User, _>(
            DeleteBehavior::Cascade,
            filter,
            None,
            crate::tests::TestDatabaseSchema,
        );
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_select_raw_record() {
        load_fixtures();
        let query = Query::builder().all().limit(10).build();
        let res = select_raw("users", query, None, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
        let rows = res.unwrap();
        assert!(!rows.is_empty());
        for row in &rows {
            assert!(row.iter().any(|(col, _)| col.name == "id"));
            assert!(row.iter().any(|(col, _)| col.name == "name"));
        }
    }

    #[test]
    fn test_should_fail_select_raw_unknown_table() {
        load_fixtures();
        let query = Query::builder().all().build();
        let res = select_raw("nonexistent", query, None, crate::tests::TestDatabaseSchema);
        assert!(res.is_err());
    }

    #[test]
    fn test_should_select_join() {
        load_fixtures();
        let query = Query::builder()
            .all()
            .inner_join("posts", "users.id", "posts.user")
            .build();
        let res = select_join("users", query, None, crate::tests::TestDatabaseSchema);
        assert!(res.is_ok());
        assert!(!res.unwrap().is_empty());
    }

    #[test]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 1111"]
    fn test_should_trap_on_unknown_transaction() {
        load_fixtures();
        let _ = commit(1111, crate::tests::TestDatabaseSchema);
    }

    #[test]
    #[ignore = "transaction ownership is restored by the ledger added in step 3 of this branch"]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 0"]
    fn test_should_not_allow_operating_wrong_tx() {
        load_fixtures();

        let _bob = Principal::from_text("ryjl3-tyaaa-aaaaa-aaaba-cai").unwrap();
        let tx_id = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());

        // try to commit the transaction started by bob (we are alice)
        let _ = commit(tx_id, crate::tests::TestDatabaseSchema);
    }
}
