//! Generic per-operation helpers consumed by the endpoints generated by
//! `#[derive(DbmsCanister)]`.
//!
//! Every helper receives the user's schema `S`, wraps it in
//! [`CanisterSchema`] so the engine sees the reserved tables too, and checks
//! the caller against the ACL through the same database it then operates on.

mod inspect;

use candid::Principal;
use ic_dbms_api::prelude::{
    AclEntry, AggregateFunction, AggregatedRow, ColumnDef, Database, DeleteBehavior, Filter,
    IcDbmsError, IcDbmsResult, InsertRecord, JoinColumnDef, MigrationOp, MigrationPolicy,
    Permission, Query, TableSchema, TransactionId, UpdateRecord, Value,
};
use wasm_dbms::prelude::{DatabaseSchema, WasmDbmsDatabase};

pub use self::inspect::inspect;
use crate::memory::{DBMS_CONTEXT, IcMemoryProvider};
use crate::schema::CanisterSchema;
use crate::{acl, trap};

/// Registers the reserved ACL table and grants [`Permission::Admin`] to every
/// principal in `principals`. Called by the generated `init` after the user
/// tables are registered.
pub fn init_acl<S>(principals: Vec<Principal>, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    DBMS_CONTEXT.with(acl::register)?;
    with_database(None, database_schema, |db| {
        for principal in principals {
            acl::grant(db, principal, Permission::Admin)?;
        }
        Ok(())
    })
}

/// Grants `permission` to `target`. Caller must hold [`Permission::Admin`].
pub fn acl_grant<S>(
    target: Principal,
    permission: Permission,
    database_schema: S,
) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        acl::require_admin(db, caller)?;
        acl::grant(db, target, permission)
    })
}

/// Revokes `permission` from `target`. Caller must hold
/// [`Permission::Admin`]. Refuses to remove the last admin.
pub fn acl_revoke<S>(
    target: Principal,
    permission: Permission,
    database_schema: S,
) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        acl::require_admin(db, caller)?;
        acl::revoke(db, target, permission)
    })
}

/// Lists every principal with its permissions. Caller must hold
/// [`Permission::Admin`].
pub fn acl_list<S>(database_schema: S) -> IcDbmsResult<Vec<AclEntry>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        acl::require_admin(db, caller)?;
        acl::list(db)
    })
}

/// Returns the caller's own permissions. Always permitted.
pub fn my_permissions<S>(database_schema: S) -> IcDbmsResult<Vec<Permission>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| acl::permissions_of(db, caller))
}

/// Begins a new transaction and returns its ID. Caller must hold
/// [`Permission::Admin`].
pub fn begin_transaction<S>(database_schema: S) -> IcDbmsResult<TransactionId>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| acl::require_admin(db, caller))?;
    Ok(DBMS_CONTEXT.with(|ctx| ctx.begin_transaction()))
}

/// Commits the transaction with the given ID.
///
/// Traps when the ID does not name an open transaction.
pub fn commit<S>(transaction_id: TransactionId, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(Some(&transaction_id));
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::from_transaction(
            ctx,
            CanisterSchema::new(database_schema),
            transaction_id,
        );
        db.commit().map_err(IcDbmsError::from)
    })
}

/// Rolls back the transaction with the given ID.
///
/// Traps when the ID does not name an open transaction.
pub fn rollback<S>(transaction_id: TransactionId, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    assert_transaction_is_open(Some(&transaction_id));
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::from_transaction(
            ctx,
            CanisterSchema::new(database_schema),
            transaction_id,
        );
        db.rollback().map_err(IcDbmsError::from)
    })
}

/// Selects typed records from table `T`, optionally inside a transaction.
/// Caller must hold [`Permission::Admin`].
pub fn select<T, S>(
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<T::Record>>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.select::<T>(query).map_err(IcDbmsError::from)
    })
}

/// Selects untyped rows from the table called `table`, optionally inside a
/// transaction. Caller must hold [`Permission::Admin`].
pub fn select_raw<S>(
    table: &str,
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<Vec<(ColumnDef, Value)>>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.select_raw(table, query).map_err(IcDbmsError::from)
    })
}

/// Runs a query with joins rooted at `table`, optionally inside a
/// transaction. Caller must hold [`Permission::Admin`].
pub fn select_join<S>(
    table: &str,
    query: Query,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<Vec<(JoinColumnDef, Value)>>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.select_join(table, query).map_err(IcDbmsError::from)
    })
}

/// Runs an aggregate query on table `T`, optionally inside a transaction.
/// Caller must hold [`Permission::Admin`].
pub fn aggregate<T, S>(
    query: Query,
    aggregates: Vec<AggregateFunction>,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<Vec<AggregatedRow>>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.aggregate::<T>(query, &aggregates)
            .map_err(IcDbmsError::from)
    })
}

/// Inserts a record into table `T`, optionally inside a transaction. Caller
/// must hold [`Permission::Admin`].
pub fn insert<T, S>(
    record: T::Insert,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<()>
where
    T: TableSchema,
    T::Insert: InsertRecord<Schema = T>,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.insert::<T>(record).map_err(IcDbmsError::from)
    })
}

/// Updates records of table `T`, optionally inside a transaction. Returns
/// the number of updated rows. Caller must hold [`Permission::Admin`].
pub fn update<T, S>(
    patch: T::Update,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<u64>
where
    T: TableSchema,
    T::Update: UpdateRecord<Schema = T>,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.update::<T>(patch).map_err(IcDbmsError::from)
    })
}

/// Deletes records of table `T`, optionally inside a transaction. Returns
/// the number of deleted rows. Caller must hold [`Permission::Admin`].
pub fn delete<T, S>(
    behaviour: DeleteBehavior,
    filter: Option<Filter>,
    transaction_id: Option<TransactionId>,
    database_schema: S,
) -> IcDbmsResult<u64>
where
    T: TableSchema,
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    assert_transaction_is_open(transaction_id.as_ref());
    with_database(transaction_id, database_schema, |db| {
        acl::require_admin(db, caller)?;
        db.delete::<T>(behaviour, filter).map_err(IcDbmsError::from)
    })
}

/// Returns whether the persisted schema differs from the compiled one.
/// Caller must hold [`Permission::Admin`] or be a controller.
pub fn has_drift<S>(database_schema: S) -> IcDbmsResult<bool>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        authorize_migration(db, caller)?;
        db.has_drift().map_err(IcDbmsError::from)
    })
}

/// Returns the migration operations needed to heal schema drift. Caller must
/// hold [`Permission::Admin`] or be a controller.
pub fn pending_migrations<S>(database_schema: S) -> IcDbmsResult<Vec<MigrationOp>>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    with_database(None, database_schema, |db| {
        authorize_migration(db, caller)?;
        db.pending_migrations().map_err(IcDbmsError::from)
    })
}

/// Applies the pending migrations under `policy`. Caller must hold
/// [`Permission::Admin`] or be a controller.
pub fn migrate<S>(policy: MigrationPolicy, database_schema: S) -> IcDbmsResult<()>
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
{
    let caller = crate::utils::caller();
    DBMS_CONTEXT.with(|ctx| {
        let mut db = WasmDbmsDatabase::oneshot(ctx, CanisterSchema::new(database_schema));
        authorize_migration(&db, caller)?;
        db.migrate(policy).map_err(IcDbmsError::from)
    })
}

/// Controllers may always run migrations: while the schema has drifted the
/// ACL table cannot be read, and controllers already hold full power over the
/// canister. Everyone else must hold [`Permission::Admin`].
fn authorize_migration(
    db: &WasmDbmsDatabase<'_, IcMemoryProvider>,
    caller: Principal,
) -> IcDbmsResult<()> {
    if crate::utils::is_controller(caller) {
        return Ok(());
    }
    acl::require_admin(db, caller)
}

/// Closure-based helper that creates a [`WasmDbmsDatabase`] over the composed
/// [`CanisterSchema`] inside the `DBMS_CONTEXT` thread-local and invokes `f`
/// on it.
fn with_database<S, F, R>(transaction_id: Option<TransactionId>, database_schema: S, f: F) -> R
where
    S: DatabaseSchema<IcMemoryProvider> + 'static,
    F: for<'a> FnOnce(&WasmDbmsDatabase<'a, IcMemoryProvider>) -> R,
{
    DBMS_CONTEXT.with(|ctx| {
        let schema = CanisterSchema::new(database_schema);
        let db = match transaction_id {
            Some(tx_id) => WasmDbmsDatabase::from_transaction(ctx, schema, tx_id),
            None => WasmDbmsDatabase::oneshot(ctx, schema),
        };
        f(&db)
    })
}

/// Traps unless `transaction_id` is `None` or names an open transaction.
fn assert_transaction_is_open(transaction_id: Option<&TransactionId>) {
    let Some(tx_id) = transaction_id else {
        return;
    };
    let caller = crate::utils::caller();
    if !DBMS_CONTEXT.with(|ctx| ctx.has_transaction(tx_id)) {
        trap!("Caller {caller} does not own transaction {tx_id}");
    }
}

#[cfg(test)]
mod tests {

    use ic_dbms_api::prelude::{AclError, Uint32};

    use super::*;
    use crate::tests::{TestDatabaseSchema, UserInsertRequest, load_fixtures};

    fn alice() -> Principal {
        crate::utils::caller()
    }

    fn bob() -> Principal {
        Principal::from_text("ryjl3-tyaaa-aaaaa-aaaba-cai").unwrap()
    }

    /// Registers the test tables and bootstraps alice as admin.
    fn bootstrap_alice() {
        DBMS_CONTEXT.with(|ctx| {
            TestDatabaseSchema::register_tables(ctx).expect("failed to register tables");
        });
        init_acl(vec![alice()], TestDatabaseSchema).expect("bootstrap acl");
    }

    fn user(id: u32) -> UserInsertRequest {
        UserInsertRequest {
            id: id.into(),
            name: "Alice".to_string().into(),
            email: "alice@example.com".into(),
            age: 25u32.into(),
        }
    }

    fn assert_access_denied<T: std::fmt::Debug>(res: IcDbmsResult<T>) {
        assert!(matches!(
            res,
            Err(IcDbmsError::Acl(AclError::AccessDenied {
                required: Permission::Admin
            }))
        ));
    }

    #[test]
    fn test_init_acl_bootstraps_admins() {
        bootstrap_alice();
        let entries = acl_list(TestDatabaseSchema).expect("list");
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].principal, alice());
        assert_eq!(
            my_permissions(TestDatabaseSchema).expect("perms"),
            vec![Permission::Admin]
        );
    }

    #[test]
    fn test_init_acl_rejects_anonymous_admin() {
        DBMS_CONTEXT.with(|ctx| {
            TestDatabaseSchema::register_tables(ctx).expect("failed to register tables");
        });
        let err = init_acl(vec![Principal::anonymous()], TestDatabaseSchema)
            .expect_err("anonymous admin");
        assert!(matches!(
            err,
            IcDbmsError::Acl(AclError::AnonymousPrincipal)
        ));
    }

    #[test]
    fn test_should_grant_and_revoke_admin() {
        bootstrap_alice();
        acl_grant(bob(), Permission::Admin, TestDatabaseSchema).expect("grant");
        assert!(
            acl_list(TestDatabaseSchema)
                .unwrap()
                .iter()
                .any(|e| e.principal == bob())
        );
        acl_revoke(bob(), Permission::Admin, TestDatabaseSchema).expect("revoke");
        assert!(
            !acl_list(TestDatabaseSchema)
                .unwrap()
                .iter()
                .any(|e| e.principal == bob())
        );
    }

    #[test]
    fn test_should_refuse_to_revoke_last_admin_through_api() {
        bootstrap_alice();
        let err = acl_revoke(alice(), Permission::Admin, TestDatabaseSchema).expect_err("last");
        assert!(matches!(err, IcDbmsError::Acl(AclError::LastAdmin)));
    }

    #[test]
    fn test_unlisted_caller_is_denied_everywhere() {
        DBMS_CONTEXT.with(|ctx| {
            TestDatabaseSchema::register_tables(ctx).expect("failed to register tables");
        });
        init_acl(vec![bob()], TestDatabaseSchema).expect("bootstrap bob");

        assert_access_denied(insert::<crate::tests::User, _>(
            user(1),
            None,
            TestDatabaseSchema,
        ));
        assert_access_denied(select::<crate::tests::User, _>(
            Query::builder().all().build(),
            None,
            TestDatabaseSchema,
        ));
        assert_access_denied(select_raw(
            "users",
            Query::builder().all().build(),
            None,
            TestDatabaseSchema,
        ));
        assert_access_denied(select_raw(
            "ic_dbms_acl",
            Query::builder().all().build(),
            None,
            TestDatabaseSchema,
        ));
        assert_access_denied(begin_transaction(TestDatabaseSchema));
        assert_access_denied(acl_grant(alice(), Permission::Admin, TestDatabaseSchema));
        assert_access_denied(acl_list(TestDatabaseSchema));
        assert_access_denied(has_drift(TestDatabaseSchema));
        assert_access_denied(migrate(MigrationPolicy::default(), TestDatabaseSchema));
        assert!(my_permissions(TestDatabaseSchema).unwrap().is_empty());
    }

    #[test]
    fn test_admin_can_read_reserved_acl_table_through_select_raw() {
        bootstrap_alice();
        let rows = select_raw(
            "ic_dbms_acl",
            Query::builder().all().build(),
            None,
            TestDatabaseSchema,
        )
        .expect("select acl");
        assert_eq!(rows.len(), 1);
    }

    #[test]
    fn test_should_begin_transaction() {
        bootstrap_alice();
        let _tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
    }

    #[test]
    fn test_should_commit_transaction() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        let res = commit(tx_id, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_rollback_transaction() {
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        let res = rollback(tx_id, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_insert_inside_transaction_and_commit() {
        load_fixtures();
        bootstrap_alice();
        let tx_id = begin_transaction(TestDatabaseSchema).expect("begin");
        insert::<crate::tests::User, _>(user(100), Some(tx_id), TestDatabaseSchema)
            .expect("insert in tx");
        commit(tx_id, TestDatabaseSchema).expect("commit");
        let rows = select::<crate::tests::User, _>(
            Query::builder()
                .all()
                .and_where(Filter::Eq("id".to_string(), Uint32::from(100u32).into()))
                .build(),
            None,
            TestDatabaseSchema,
        )
        .expect("select");
        assert_eq!(rows.len(), 1);
    }

    #[test]
    fn test_should_insert_record() {
        load_fixtures();
        bootstrap_alice();
        let res = insert::<crate::tests::User, _>(user(100), None, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_select_record() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder().all().limit(10).build();
        let res = select::<crate::tests::User, _>(query, None, TestDatabaseSchema);
        assert!(res.is_ok());
        let records = res.unwrap();
        assert!(!records.is_empty());
    }

    #[test]
    fn test_should_update_record() {
        load_fixtures();
        bootstrap_alice();

        let patch = crate::tests::UserUpdateRequest {
            id: None,
            name: Some("Robert".into()),
            email: Some("robert@example.com".into()),
            age: None,
            where_clause: Some(Filter::Eq("id".to_string(), Uint32::from(1u32).into())),
        };
        let res = update::<crate::tests::User, _>(patch, None, TestDatabaseSchema);
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_delete_record() {
        load_fixtures();
        bootstrap_alice();

        let filter = Some(Filter::Eq("id".to_string(), Uint32::from(2u32).into()));
        let res = delete::<crate::tests::User, _>(
            DeleteBehavior::Cascade,
            filter,
            None,
            TestDatabaseSchema,
        );
        assert!(res.is_ok());
    }

    #[test]
    fn test_should_aggregate() {
        load_fixtures();
        bootstrap_alice();
        let res = aggregate::<crate::tests::User, _>(
            Query::builder().all().build(),
            vec![AggregateFunction::Count(None)],
            None,
            TestDatabaseSchema,
        );
        assert!(res.is_ok());
        assert_eq!(res.unwrap().len(), 1);
    }

    #[test]
    fn test_should_select_raw_record() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder().all().limit(10).build();
        let res = select_raw("users", query, None, TestDatabaseSchema);
        assert!(res.is_ok());
        let rows = res.unwrap();
        assert!(!rows.is_empty());
        for row in &rows {
            assert!(row.iter().any(|(col, _)| col.name == "id"));
            assert!(row.iter().any(|(col, _)| col.name == "name"));
        }
    }

    #[test]
    fn test_should_fail_select_raw_unknown_table() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder().all().build();
        let res = select_raw("nonexistent", query, None, TestDatabaseSchema);
        assert!(res.is_err());
    }

    #[test]
    fn test_should_select_join() {
        load_fixtures();
        bootstrap_alice();
        let query = Query::builder()
            .all()
            .inner_join("posts", "users.id", "posts.user")
            .build();
        let res = select_join("users", query, None, TestDatabaseSchema);
        assert!(res.is_ok());
        assert!(!res.unwrap().is_empty());
    }

    #[test]
    fn test_migration_endpoints_report_no_drift_for_admin() {
        load_fixtures();
        bootstrap_alice();
        assert!(!has_drift(TestDatabaseSchema).expect("has_drift"));
        assert!(
            pending_migrations(TestDatabaseSchema)
                .expect("pending")
                .is_empty()
        );
        migrate(MigrationPolicy::default(), TestDatabaseSchema).expect("noop migrate");
    }

    #[test]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 1111"]
    fn test_should_trap_on_unknown_transaction() {
        load_fixtures();
        bootstrap_alice();
        let _ = commit(1111, TestDatabaseSchema);
    }

    #[test]
    #[ignore = "transaction ownership is restored by the ledger added in step 3 of this branch"]
    #[should_panic = "Caller ghsi2-tqaaa-aaaan-aaaca-cai does not own transaction 0"]
    fn test_should_not_allow_operating_wrong_tx() {
        load_fixtures();
        bootstrap_alice();

        let tx_id = DBMS_CONTEXT.with(|ctx| ctx.begin_transaction());

        let _ = commit(tx_id, TestDatabaseSchema);
    }
}
